/*
	Exploratory Data Analysis (EDA)
	Consists in 6 steps of exploratory actions helpng to undestand the Data on the business
*/
--=======================================================================
-- 05 >> Magnitude Analysis
--=======================================================================
-- Find total customers by countries
SELECT country, COUNT(customer_key) AS customers_by_country
FROM gold.dim_customers
GROUP BY country

-- Find total customers by gender
SELECT gender, COUNT(customer_key) AS customers_by_gender
FROM gold.dim_customers
GROUP BY gender

-- Find total products by category
SELECT category, COUNT(product_key) AS products_by_category
FROM gold.dim_products
GROUP BY category
ORDER BY products_by_category

-- What is the average cost in each category?
SELECT category, AVG(cost) as average_cost_per_categtory
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost_per_categtory

-- What is the total revenue generated for each category?
SELECT 
	p.category, 
	SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Find total revenue is generated by each customer
SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT 
	c.country,
	SUM(s.quantity) AS total_sold_items	
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC
